#!/usr/bin/env bash
# Render and apply Kubernetes manifests.
# Manifest templates are rendered via envsubst using values from config/lab.env,
# which is generated by Terraform. Directories are processed in dependency order:
# namespaces first within each directory, then remaining resources.
# Requires: kubectl and envsubst are available on the host.

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

LAB_ENV="${CONFIG_DIR}/lab.env"
MANIFESTS_DIR="${LAB_DIR}/manifests"
# Order matters: networking (cluster-scoped Cilium resources) must come before
# gateway (needs the namespace first, then the Gateway), and monitoring
# (HTTPRoutes) must come last as they reference the Gateway.
MANIFEST_DIRS=(networking gateway monitoring)

if ! command -v envsubst &>/dev/null; then
    echo "Error: envsubst is not installed or not in PATH" >&2
    exit 1
fi

if [[ ! -f "${LAB_ENV}" ]]; then
    echo "Error: ${LAB_ENV} not found — run 'terraform apply' first" >&2
    exit 1
fi

set -a
source "${LAB_ENV}"
set +a

for dir in "${MANIFEST_DIRS[@]}"; do
    echo "Applying ${MANIFESTS_DIR}/${dir}..."
    {
        [[ -f "${MANIFESTS_DIR}/${dir}/namespace.yaml" ]] \
            && printf '%s/%s/namespace.yaml\n' "${MANIFESTS_DIR}" "${dir}"
        find "${MANIFESTS_DIR}/${dir}" -name '*.yaml' ! -name 'namespace.yaml' | sort
    } | while read -r f; do
        envsubst '${CILIUM_GATEWAY_IP} ${CILIUM_LB_POOL_CIDR}' < "${f}"
        printf '\n---\n'
    done | kubectl --kubeconfig "${KUBECONFIG}" apply --server-side -f -
done

echo "--- Manifests applied"
